name: Release Installer

on:
  push:
    branches: [main]

jobs:
  getVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Get next version
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true 
    outputs:
      version: ${{ steps.taggerDryRun.outputs.new_tag }}

  build:
    runs-on: windows-latest
    needs: getVersion
    steps:
      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ needs.getVersion.outputs.version }}"
      - uses: actions/checkout@v3
      - name: Get next version
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt
      - name: Build exe
        run: |
          scripts\buildWindows.bat
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: HoneyBadgerInstaller.exe
          path: 'scripts\Output\HoneyBadgerInstaller.exe'

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Tag version
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
